# S&P 500 tickers (as of Aug 2026)
# Source: Compiled from public S&P Global membership list
SP500_TICKERS = [
    "A", "AAPL", "ABBV", "ABC", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI",
    "ADM", "ADP", "ADSK", "AEP", "AEIS", "AFL", "AG", "AIG", "AIZ", "AJG",
    "AKAM", "ALB", "ALGN", "ALL", "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP",
    "AMT", "AMZN", "ANSS", "AON", "APA", "APD", "APH", "APTV", "ARE", "ATO",
    "AVB", "AVGO", "AVY", "AWK", "AXON", "AZO", "BA", "BAC", "BALL", "BAND",
    "BDX", "BEN", "BF-B", "BIIB", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMRN",
    "BMY", "BR", "BRO", "BSX", "BURL", "BWA", "BX", "BXLT", "BYD", "BZ",
    "C", "CAG", "CAH", "CARR", "CAT", "CB", "CBOE", "CBRE", "CCL", "CHD",
    "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA", "CME", "CMG",
    "CMI", "CMS", "CNC", "CNH", "COF", "COO", "COP", "COR", "COST", "CPT",
    "CRL", "CRM", "CSCO", "CSGP", "CSL", "CSS", "CTAS", "CTLT", "CTRA", "CTSH",
    "CTVA", "CVS", "CVX", "CZR", "D", "DASH", "DAY", "DD", "DE", "DECK",
    "DEL", "DELL", "DG", "DGX", "DHI", "DHR", "DIS", "DLR", "DLTR", "DOV",
    "DOW", "DPZ", "DRI", "DTE", "DUK", "DXC", "DXCM", "EA", "EBAY", "ECL",
    "ED", "EG", "EGH", "EIX", "EL", "ELV", "EMN", "EMR", "ENPH", "EOG",
    "EPAM", "EQIX", "EQR", "EQT", "ERIE", "ES", "ESS", "EWH", "EWM", "EWS",
    "EXC", "EXCH", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS",
    "FDX", "FE", "FF", "FI", "FICO", "FIS", "FITB", "FLT", "FMC", "FN",
    "FNGU", "FOXA", "FRC", "FRT", "FSLR", "FTNT", "FTV", "G", "GAT", "GDDY",
    "GE", "GEHC", "GEN", "GILD", "GIS", "GL", "GLW", "GM", "GNRC", "GOOG",
    "GOOGL", "GPC", "GPN", "GRMN", "GRUB", "GS", "GWW", "HAL", "HAS", "HBAN",
    "HCA", "HD", "HES", "HII", "HLT", "HMC", "HOG", "HOLX", "HON", "HPE",
    "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBM", "ICE",
    "IDXX", "IEX", "IFF", "INCY", "INGR", "INTC", "INTU", "INVH", "IONQ", "IQV",
    "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JBL", "JCI", "JKHY",
    "JM", "JNJ", "JNPR", "JPM", "JUN", "K", "KDP", "KEY", "KEYS", "KHC",
    "KIM", "KLAC", "KMB", "KMI", "KMX", "KO", "KR", "KSS", "KT", "L",
    "LAUR", "LDOS", "LEN", "LHX", "LH", "LII", "LLY", "LMT", "LNC", "LNG",
    "LNT", "LOW", "LRCX", "LUV", "LVS", "LW", "LYB", "LYV", "M", "MA", "MAA",
    "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDGL", "MDLZ", "MDT", "MED",
    "MELI", "META", "MGM", "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM", "MNST",
    "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MRO", "MS", "MSCI", "MSFT",
    "MTCH", "MTD", "MU", "NDAQ", "NDSN", "NEE", "NEM", "NET", "NFLX", "NI",
    "NKE", "NOC", "NOT", "NOV", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE",
    "NVDA", "NVR", "NXPI", "O", "ODFL", "OG", "OKE", "ON", "ORCL", "ORLY", "OSK",
    "OXY", "PANW", "PAR", "PAYC", "PAYX", "PCAR", "PCG", "PCI", "PD", "PEG",
    "PEN", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PLTR",
    "PM", "PNC", "PNR", "PNW", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX",
    "PTC", "PVH", "PWR", "PXD", "PYPL", "QCOM", "QD", "RCL", "REG", "REGN",
    "RF", "RHI", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG",
    "RTX", "RVTY", "S", "SALT", "SAM", "SAP", "SCHW", "SEDG", "SEE", "SEG",
    "SF", "SHW", "SJM", "SKX", "SLB", "SLG", "SMAR", "SMCI", "SNA", "SNPS",
    "SNX", "SO", "SOLV", "SPG", "SPGI", "SPOT", "SRE", "STE", "STLD", "STM",
    "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", "TAP",
    "TDG", "TDY", "TECH", "TEAM", "TER", "TFC", "TFX", "TGT", "TJX", "TK",
    "TMO", "TMUS", "TNG", "TPR", "TPL", "TRGP", "TRMB", "TROW", "TRV", "TSCO",
    "TSLA", "TSN", "TT", "TTWO", "TXN", "TXT", "TYL", "UA", "UDR", "UHS",
    "ULTA", "UNH", "UNP", "UNVR", "UPS", "UPST", "URI", "USB", "V", "VARS",
    "VEEV", "VFC", "VIAC", "VICI", "VLO", "VLTO", "VMC", "VMI", "VMW", "VNO",
    "VOD", "VRSK", "VRSN", "VRTX", "VST", "VTRS", "VZ", "W", "WAB", "WAT",
    "WBA", "WBD", "WCN", "WDC", "WEC", "WELL", "WFC", "WHR", "WKB", "WM",
    "WMB", "WMT", "WNR", "WPP", "WSO", "WSOG", "WTW", "WY", "WYNN", "XEL",
    "XOM", "XPO", "XRAY", "XYL", "YUM", "ZBH", "ZBRA", "ZION", "ZTS",
]
